### ISSUE TITLE
Fails to build on Python 3.11 - longintrepr.h: file not found

### ISSUE THREAD

**Issue by glensc** [ideler/python-strtotime#1]
Fails with:

```
      strtotime.c:196:12: fatal error: 'longintrepr.h' file not found
        #include "longintrepr.h"
                 ^~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
```

<details>

```
➜ pip install strtotime
Collecting strtotime
  Using cached strtotime-1.0.3.zip (598 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: strtotime
  Building wheel for strtotime (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'strtotime' extension
      creating build
      creating build/temp.macosx-10.15-x86_64-cpython-311
      creating build/temp.macosx-10.15-x86_64-cpython-311/lib
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -DHAVE_STRING_H=1 -I. -Ilib -I/usr/local/lib/python-3.11.1/include -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c lib/astro.c -o build/temp.macosx-10.15-x86_64-cpython-311/lib/astro.o -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -Wno-expansion-to-defined -Wno-nullability-completeness -Wno-unreachable-code
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -DHAVE_STRING_H=1 -I. -Ilib -I/usr/local/lib/python-3.11.1/include -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c lib/dow.c -o build/temp.macosx-10.15-x86_64-cpython-311/lib/dow.o -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -Wno-expansion-to-defined -Wno-nullability-completeness -Wno-unreachable-code
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -DHAVE_STRING_H=1 -I. -Ilib -I/usr/local/lib/python-3.11.1/include -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c lib/parse_date.c -o build/temp.macosx-10.15-x86_64-cpython-311/lib/parse_date.o -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -Wno-expansion-to-defined -Wno-nullability-completeness -Wno-unreachable-code
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -DHAVE_STRING_H=1 -I. -Ilib -I/usr/local/lib/python-3.11.1/include -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c lib/parse_tz.c -o build/temp.macosx-10.15-x86_64-cpython-311/lib/parse_tz.o -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -Wno-expansion-to-defined -Wno-nullability-completeness -Wno-unreachable-code
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -DHAVE_STRING_H=1 -I. -Ilib -I/usr/local/lib/python-3.11.1/include -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c lib/timelib.c -o build/temp.macosx-10.15-x86_64-cpython-311/lib/timelib.o -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -Wno-expansion-to-defined -Wno-nullability-completeness -Wno-unreachable-code
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -DHAVE_STRING_H=1 -I. -Ilib -I/usr/local/lib/python-3.11.1/include -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c lib/tm2unixtime.c -o build/temp.macosx-10.15-x86_64-cpython-311/lib/tm2unixtime.o -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -Wno-expansion-to-defined -Wno-nullability-completeness -Wno-unreachable-code
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -DHAVE_STRING_H=1 -I. -Ilib -I/usr/local/lib/python-3.11.1/include -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c lib/unixtime2tm.c -o build/temp.macosx-10.15-x86_64-cpython-311/lib/unixtime2tm.o -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -Wno-expansion-to-defined -Wno-nullability-completeness -Wno-unreachable-code
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -DHAVE_STRING_H=1 -I. -Ilib -I/usr/local/lib/python-3.11.1/include -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c strtotime.c -o build/temp.macosx-10.15-x86_64-cpython-311/strtotime.o -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -Wno-expansion-to-defined -Wno-nullability-completeness -Wno-unreachable-code
      strtotime.c:196:12: fatal error: 'longintrepr.h' file not found
        #include "longintrepr.h"
                 ^~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for strtotime
  Running setup.py clean for strtotime
Failed to build strtotime
Installing collected packages: strtotime
  Running setup.py install for strtotime ... error
  error: subprocess-exited-with-error

  × Running setup.py install for strtotime did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      running install
      /usr/local/lib/python-3.11.1/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      building 'strtotime' extension
      creating build
      creating build/temp.macosx-10.15-x86_64-cpython-311
      creating build/temp.macosx-10.15-x86_64-cpython-311/lib
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -DHAVE_STRING_H=1 -I. -Ilib -I/usr/local/lib/python-3.11.1/include -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c lib/astro.c -o build/temp.macosx-10.15-x86_64-cpython-311/lib/astro.o -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -Wno-expansion-to-defined -Wno-nullability-completeness -Wno-unreachable-code
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -DHAVE_STRING_H=1 -I. -Ilib -I/usr/local/lib/python-3.11.1/include -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c lib/dow.c -o build/temp.macosx-10.15-x86_64-cpython-311/lib/dow.o -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -Wno-expansion-to-defined -Wno-nullability-completeness -Wno-unreachable-code
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -DHAVE_STRING_H=1 -I. -Ilib -I/usr/local/lib/python-3.11.1/include -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c lib/parse_date.c -o build/temp.macosx-10.15-x86_64-cpython-311/lib/parse_date.o -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -Wno-expansion-to-defined -Wno-nullability-completeness -Wno-unreachable-code
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -DHAVE_STRING_H=1 -I. -Ilib -I/usr/local/lib/python-3.11.1/include -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c lib/parse_tz.c -o build/temp.macosx-10.15-x86_64-cpython-311/lib/parse_tz.o -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -Wno-expansion-to-defined -Wno-nullability-completeness -Wno-unreachable-code
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -DHAVE_STRING_H=1 -I. -Ilib -I/usr/local/lib/python-3.11.1/include -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c lib/timelib.c -o build/temp.macosx-10.15-x86_64-cpython-311/lib/timelib.o -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -Wno-expansion-to-defined -Wno-nullability-completeness -Wno-unreachable-code
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -DHAVE_STRING_H=1 -I. -Ilib -I/usr/local/lib/python-3.11.1/include -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c lib/tm2unixtime.c -o build/temp.macosx-10.15-x86_64-cpython-311/lib/tm2unixtime.o -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -Wno-expansion-to-defined -Wno-nullability-completeness -Wno-unreachable-code
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -DHAVE_STRING_H=1 -I. -Ilib -I/usr/local/lib/python-3.11.1/include -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c lib/unixtime2tm.c -o build/temp.macosx-10.15-x86_64-cpython-311/lib/unixtime2tm.o -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -Wno-expansion-to-defined -Wno-nullability-completeness -Wno-unreachable-code
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -DHAVE_STRING_H=1 -I. -Ilib -I/usr/local/lib/python-3.11.1/include -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c strtotime.c -o build/temp.macosx-10.15-x86_64-cpython-311/strtotime.o -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -Wno-expansion-to-defined -Wno-nullability-completeness -Wno-unreachable-code
      strtotime.c:196:12: fatal error: 'longintrepr.h' file not found
        #include "longintrepr.h"
                 ^~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> strtotime

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

```

</details>

**Comment by glensc** [comment]
Seems this is rather python 3.11 issue, installed ok with python 3.10:

```
➜ pip install strtotime
Collecting strtotime
  Using cached strtotime-1.0.3.zip (598 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: strtotime
  Building wheel for strtotime (setup.py) ... done
  Created wheel for strtotime: filename=strtotime-1.0.3-cp310-cp310-macosx_10_15_x86_64.whl size=270418 sha256=2876386e9a6a655943ca238f077c5d54e648c9899ffc527b3feeb1965f294852
  Stored in directory: /Users/glen/Library/Caches/pip/wheels/93/d3/4f/a302fc89b457c5393ed8da438ec7d538ab990dd6893b5f62f4
Successfully built strtotime
Installing collected packages: strtotime
Successfully installed strtotime-1.0.3
```

**Comment by glensc** [comment]
Similar issue, but not sure what the fix was:
- https://github.com/aio-libs/aiohttp/issues/6600

**Comment by nick-traeger** [comment]
We have rebuilt the packages again and the error seems to be fixed by this.

**Comment by glensc** [comment]
I don't understand how your build fixes something for me, your publish only manylinux1 wheels for py3.5-3.9, but I'm on macos not linux.

however it installed now, but this is different computer now
```
✖  pip install strtotime
Collecting strtotime
  Downloading strtotime-1.0.4.zip (600 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 600.1/600.1 kB 5.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: strtotime
  Building wheel for strtotime (setup.py) ... done
  Created wheel for strtotime: filename=strtotime-1.0.4-cp311-cp311-macosx_13_0_arm64.whl size=268150 sha256=12f74762bc5c91183ab85792253a92cf7b8ffe630c3a4944306db1c280d46f08
  Stored in directory: /Users/glen/Library/Caches/pip/wheels/6b/1c/a5/fdd1191e0ccd57cf2e74442c63dbec357d453680f98a08012a
Successfully built strtotime
Installing collected packages: strtotime
Successfully installed strtotime-1.0.4
```

it's weird because there are no source commits to this repository...

i downloaded source from pip and compared with git repository, and some files are not tracked:

```
➜ diff -u python-strtotime/ strtotime-1.0.4/
Only in python-strtotime: .git
Only in python-strtotime: .gitignore
Only in python-strtotime: .gitlab-ci.yml
Only in python-strtotime: .gitmodules
Only in strtotime-1.0.4: PKG-INFO
Only in python-strtotime: build.sh
Common subdirectories: python-strtotime/lib and strtotime-1.0.4/lib
diff -u python-strtotime/setup.cfg strtotime-1.0.4/setup.cfg
--- python-strtotime/setup.cfg	2023-01-13 12:57:19
+++ strtotime-1.0.4/setup.cfg	2023-01-13 09:56:36
@@ -1,2 +1,7 @@
 [sdist]
-formats=zip
+formats = zip
+
+[egg_info]
+tag_build =
+tag_date = 0
+
Only in strtotime-1.0.4: strtotime.c
Only in strtotime-1.0.4: strtotime.egg-info
Only in python-strtotime: test_timelib.py
Only in python-strtotime: tox.ini
```

`strtotime.c` seems to be generated by Cython 0.29.33, should it be tracked in git? for security reasons?
